image: drone/scipy:2.7
script: 
    - pip install -r requirements.txt
    - pip install python-dateutil pytz pytest pytest-cov pytest-pep8
    - pip install -e .
    - py.test
    - python setup.py sdist --formats gztar

deploy:
  ssh:
    target: $SERVER
    artifacts:
      - dist/*
