language: python
python:
    - 2.7
    - 3.4
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-scipy python-nose python-matplotlib
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - pip install python-dateutil
    - pip install pytz
install:
    - pip install -e .
script: 
    - nosetests
