version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest
      - test-3.6
jobs:
  test-latest: &test-template
    docker:
      - image: circleci/python:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            echo "deb http://httpredir.debian.org/debian buster main non-free contrib" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://httpredir.debian.org/debian buster main non-free contrib" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update -yy
            sudo apt-get build-dep -yy python-numpy fftw3
            sudo apt-get install -yy fftw3-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[tests,docs]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
